[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.api-gateway]
name = "API Gateway"
port = 8000

[services.redis]
name = "Redis Streams"
image = "redis:7-alpine"
volumes = ["/data"]

[services.postgres]
name = "PostgreSQL"
image = "postgres:15"
volumes = ["/var/lib/postgresql/data"]

[[services.postgres.env]]
POSTGRES_DB = "blackswan"
POSTGRES_USER = "blackswan"
POSTGRES_PASSWORD = "${{ POSTGRES_PASSWORD }}"